
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: root

development:
  <<: *default
  database: desconto_inss_dev


test:
  <<: *default
  database: desconto_inss_test

production:
  <<: *default
  database: desconto_inss
